DROP TABLE IF EXISTS Images;
CREATE TABLE IF NOT EXISTS Images (ImageId INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, ImageName TEXT NOT NULL UNIQUE, AltText TEXT NOT NULL, Created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL);
