DROP TABLE IF EXISTS Images;
CREATE TABLE IF NOT EXISTS Images (ImageId INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, ImageName TEXT NOT NULL, AltText TEXT NOT NULL, FileName TEXT NOT NULL UNIQUE, ContentType TEXT NOT NULL, Created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL);
